version: '3.6'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: 'test'
      POSTGRES_USER: 'tester'
      POSTGRES_PASSWORD: 'test123'
    ports:
      - "5432:5432"